### ISSUE TITLE
Driver flow: show addresses in summary field

### ISSUE THREAD

**Issue by conradbielitz** [portato-io/portatoapp#128]
**How to file an issue:**

- Fill in info below.
- If more information becomes available please update fields.
- Please always add the issue to the SW bug board (project) for prioritization.

**When/where was it happening:**
Summary page showed empty fields for pick up and delivery

**What is happening, step by step:**
when registering a single trip route

**Can it be reproduced? If yes, how?:**

**Plots/screenshots/links to datasets:**
<img width="198" alt="image" src="https://github.com/portato-io/portatoapp/assets/127381972/9fc75bea-17b0-4820-874a-c360d9ea6686">

**Comment by conradbielitz** [comment]
Also happens for recurring ride

**Comment by mAkeddar** [comment]
I need to double-check with @hugo2410 if the right version is deployed

**Comment by conradbielitz** [comment]
Seems to work now
