### ISSUE TITLE
Upload button disappears behind next button

### ISSUE THREAD

**Issue by conradbielitz** [portato-io/portatoapp#60]
**How to file an issue:**

- Fill in info below.
- If more information becomes available please update fields.
- Please always add the issue to the SW bug board (project) for prioritization.

**When/where was it happening:**
Anytime when opening the app.

**What is happening, step by step:**
Screen seems to be too high and disappears behind buttons. Most pronounced when opening the app via browser, because the bottom bar takes up screen height. It's less an issue when opening the app via homescreen icon but still there.

**Can it be reproduced? If yes, how?:**
Yes, anytime

**Plots/screenshots/links to datasets:**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/127381972/236164728-3b41faaf-5b2a-48d9-8e99-e177eb45cd9d.png">

**Comment by mAkeddar** [comment]
Fixed with scrolling if @hugo2410 can confirm.

**Comment by hugo2410** [comment]
@mAkeddar, just checked on main doesnt seemed to be fixed
[Screencast from 08-05-2023 11:30:29.webm](https://user-images.githubusercontent.com/26309414/236789319-76a470b0-82c5-49c3-bec4-8edc17e3edab.webm)

**Comment by hugo2410** [comment]
Yeah, that works, i'll deploy it such that @conradbielitz can test it to see if its still happening on his screen.

**Comment by hugo2410** [comment]
@conradbielitz deployment is done, refresh the cache and try it

**Comment by conradbielitz** [comment]
Yes, can confirm that it works on iPhone both Safari and Chrome!
Super cool guys!
